name: Deploy to Firebase

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - trigger_action
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest

      - name: Download Tailwind CSS binary
        run: |
          curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o tailwindcss
          chmod +x tailwindcss
          sudo mv tailwindcss /usr/local/bin/tailwindcss

      - name: Init content modules
        run: |
          go mod init github.com/swlacy/swlacycom
          go get -u github.com/swlacy/swlacycom-content
          go mod tidy

      - name: Build CSS with Tailwind
        run: tailwindcss --input tailwind.css --output ../assets/main.css --minify
        working-directory: ./themes/swlacycom/tailwind

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWLACY_COM }}"
          channelId: live
